image-builder:
  tags:
    - docker

  stage: build
  services:
    - docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t mzapf/ansible-runner:stable .
    - docker push mzapf/ansible-runner:stable
  after_script:
    - docker logout
  only:
    - master