services:
- docker:dind


stages:
- build
- push

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t mzapf/ansible-runner:stable .
  only:
    - master

push:
  stage: push
  tags:
    - docker
  script:
    - docker push mzapf/ansible-runner:stable
  after_script:
    - docker logout
  only:
    - master