image-builder:
  tags:
    - docker

  image: docker
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t mzapf/pub-image-lib:ansible-runnerv1 .
  after_script:
    - docker image save -o docker-image-builder.tar mzapf/pub-image-lib:ansible-runnerv1
    - docker push mzapf/pub-image-lib:ansible-runnerv1
    - docker logout
  artifacts:
   paths:
    - docker-image-builder.tar
  only:
    - master