image-builder:
  tags:
    - docker

  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t mzapf/ansible-runner:stable .
  after_script:
    - docker push mzapf/ansible-runner:stable
    - docker logout
  only:
    - master