image-builder:
  tags:
    - docker
    
  image: docker:dind
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t mzapf/pub-image-lib:ansible-runnerv2 .
  after_script:
    - docker image save -o docker-image-builder.tar mzapf/pub-image-lib:ansible-runnerv2
    - docker push mzapf/pub-image-lib:ansible-runnerv2
    - docker logout
  artifacts:
   paths:
    - docker-image-builder.tar
  only:
    - master