on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{secrets.CI_REGISTRY_USER}}
        password: ${{secrets.CI_REGISTRY_PASSWORD}}
        registry: ghcr.io
        
    - name: Build the Docker image
      run: docker build -t ghcr.io/syntax3rror404/ansible-runner:latest .

    - name: Push the Docker image
      run: docker push ghcr.io/syntax3rror404/ansible-runner:latest
